# core/exporters.py
"""Export analysis results to CSV, JSON, or standalone Python scripts."""

import json
from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd

from core.constants import IST


def _timestamped_filename(prefix: str, ext: str) -> str:
    """Generate a timestamped filename."""
    ts = datetime.now(IST).strftime("%Y-%m-%d_%H%M%S")
    return f"{prefix}_{ts}.{ext}"


def export_csv(df: pd.DataFrame, prefix: str, output_dir: str = ".") -> str:
    """Export DataFrame to a timestamped CSV file."""
    filename = _timestamped_filename(prefix, "csv")
    filepath = Path(output_dir) / filename
    df.to_csv(filepath, index=False)
    return str(filepath)


def export_json(
    df: pd.DataFrame, prefix: str,
    metadata: dict[str, Any] | None = None,
    output_dir: str = ".",
) -> str:
    """Export DataFrame to JSON with metadata."""
    filename = _timestamped_filename(prefix, "json")
    filepath = Path(output_dir) / filename
    output = {
        "metadata": metadata or {},
        "data": df.to_dict(orient="records"),
        "exported_at": datetime.now(IST).isoformat(),
    }
    with open(filepath, "w") as f:
        json.dump(output, f, indent=2, default=str)
    return str(filepath)


def export_python(
    skill_name: str,
    params: dict[str, Any],
    output_dir: str = ".",
) -> str:
    """Generate a standalone Python script that reproduces the analysis."""
    filename = _timestamped_filename(skill_name, "py")
    filepath = Path(output_dir) / filename

    params_str = json.dumps(params, indent=4)
    code = f'''#!/usr/bin/env python3
"""Standalone script generated by NSE Stock Analysis Skills.
Skill: {skill_name}
Generated: {datetime.now(IST).isoformat()}

Run: python {filename}
Requires: pip install yfinance pandas
"""

import yfinance as yf
import pandas as pd

# Parameters used
params = {params_str}


def main():
    """Reproduce the {skill_name} analysis."""
    print(f"Running {skill_name} with params: {{params}}")
    # TODO: Add skill-specific analysis code
    print("Analysis complete.")


if __name__ == "__main__":
    main()
'''
    with open(filepath, "w") as f:
        f.write(code)
    return str(filepath)
